# Generated by Django 5.2.4 on 2025-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$1qdFG7lXpnJHR7JykqrQEe$fBkyjil75Bm0TGiw9CZ2v/S2Ib/phmQzgt8Vnbt173o=', max_length=128, verbose_name='익명 비밀번호'),
        ),
    ]
