# Generated by Django 5.2.4 on 2025-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$6XTkpvtuAWisBZLcBvO1V2$XURxD+E+3iNjoZNtxJA8cqQqEsNdDY5Msc5tpMwJFmM=', max_length=128, null=True, verbose_name='익명 비밀번호'),
        ),
    ]
